version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/react-native-multi-slider
    steps:
      - checkout
      - run: yarn install
      - run: git remote add beedeez https://github.com/beedeez/react-native-multi-slider.git
      - run: git config --global user.email "morgan.laupies@gmail.com" && git config --global user.name "Morgan Laupies" && git pull beedeez master && git add . && git commit -a -m "[skip ci] circle ci build and publish version patch" --allow-empty
      - run: npm version patch
      - run: npm publish
      - run: git pull beedeez master
      - run: git commit -a -m "[skip ci] release version" --allow-empty
      - run: git push --tags beedeez master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
